### PR TITLE
Add GPU example

### PR DESCRIPTION
**Pull request by roflmaostc**
@gdalle maybe like this?

I add a regularizer later.
So let's not merge yet

### CODE REVIEW

**Comment by gdalle** [comment]
looks good to me

**Comment by gdalle** [comment]
Note that if you want more speed you can prepare the differentiation operators:

https://gdalle.github.io/DifferentiationInterface.jl/DifferentiationInterface/stable/operators/#Operators-Preparation

It won't change anything for the gradient with Zygote, but it will be crucial with ReverseDiff. Not sure how much pedagogical value there is in doing that in front of the students though

**Comment by roflmaostc** [comment]
I see, maybe I skip for now since I also skipped FFT plans.
On CUDA this runs anyway in < 0.2s.

Your laptop has CUDA? Shall we run it there? Or do we do a SSH tunnel? Then we would use my laptop?

**Comment by gdalle** [comment]
My laptop has CUDA but it's deactivated and I'm wary of fiddling with the GPU settings. I'd prefer you open an SSH if you're confident it works

**Comment by roflmaostc** [comment]
Yeah, then let's use my computer.
Just to be safe, maybe send me a SSH key which I add before the session just in case my laptop dies haha

**Comment by gdalle** [comment]
You mean to connect to your computer from mine?

**Comment by roflmaostc** [comment]
Yeah, let's do with my laptop but it has seen better times. So just in case.
But SSH tunnel should work, then we can run both notebooks on my desktop in the office.

**Pull request merged**
